openapi: 3.1.0
info:
  title: Aerosol API Specification - OpenAPI 3.1
  description: |-
    This is the API implemented by any valid Aerosol server based on the OpenAPI 3.1 specification.

  license:
    name: MIT
    url: https://github.com/AkiraPinemoon/Aerosol/blob/main/LICENSE
  version: 0.1.0

paths:
  /file:
    get:
      summary: Downloads a file from the server
      description: Downloads a file from the server by filename
      parameters:
        - name: filename
          in: query
          description: The path of the requested file relative to the Vaul root
          required: true
          explode: true
          schema:
            type: string
      security:
        - accessBearer:
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  contents:
                    type: string
        "401":
          description: Unauthorized
        "404":
          description: File not present on the server

    put:
      summary: Called when a file has been created or changed on the client
      description: Uploads the new file to the server
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/File"
        required: true
      security:
        - accessBearer:
      responses:
        "200":
          description: Successful operation
        "401":
          description: Unauthorized

    delete:
      summary: Deletes a file from the server
      description: Deletes the specified file from the server
      parameters:
        - name: filename
          in: query
          description: The path of the requested file relative to the Vaul root
          required: true
          explode: true
          schema:
            type: string
      security:
        - accessBearer:
      responses:
        "200":
          description: Successful operation
        "401":
          description: Unauthorized
        "404":
          description: File not present on the server

    patch:
      summary: Renames a file on the server
      description: Renames a file from filename to newFilename
      parameters:
        - name: filename
          in: query
          description: The current path of the requested file relative to the Vaul root
          required: true
          explode: true
          schema:
            type: string
        - name: newFilename
          in: query
          description: The new path of the requested file relative to the Vaul root
          required: true
          explode: true
          schema:
            type: string
      security:
        - accessBearer:
      responses:
        "200":
          description: Successful operation
        "401":
          description: Unauthorized
        "404":
          description: File not present on the server
  /checksum:
    get:
      summary: Query server for a file or vault checksum
      description: Query server for a file or vault checksum. If filename is present the files checksum is returned, otherwise the Vault checksum
      parameters:
        - name: filename
          in: query
          description: The path of the requested file relative to the Vaul root
          required: false
          explode: true
          schema:
            type: string
      security:
        - accessBearer:
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  checksum:
                    type: string
        "401":
          description: Unauthorized
        "404":
          description: File not present on the server

  /checksums:
    get:
      summary: Query server for a folders child checksums
      description: Query server for the checksums of all direct children of a given path.
      parameters:
        - name: filename
          in: query
          description: The path of the requested folder relative to the Vaul root
          required: true
          explode: true
          schema:
            type: string
      security:
        - accessBearer:
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
        "400":
          description: Requested path was a file not a folder
        "401":
          description: Unauthorized
        "404":
          description: Folder not present on the server

  /user:
    post:
      summary: Registers a new user
      description: Registers a new user on the server (and their passkey) using a registration token returning a jwt
      requestBody:
        content:
          application/json:
            schema:
              required:
                - token
                - username
              type: object
              properties:
                token:
                  type: string
                username:
                  type: string
        required: true
      responses:
        "200":
          description: Successful operation
          headers:
            Authorization:
              description: long lived refresh JWT
              $ref: "#/components/headers/JWT"
        "401":
          description: registration token is invalid

    get:
      summary: Renew Access JWT
      description: Generate a new Acces JWT using the refresh JWT
      security:
        - refreshBearer:
      responses:
        "200":
          description: Successful operation
          headers:
            Authorization:
              $ref: "#/components/headers/JWT"
          content:
            application/json:
              schema:
                type: object
                properties:
                  expiresIn:
                    type: number
        "401":
          description: registration token is invalid

components:
  schemas:
    File:
      required:
        - filename
        - contents
      type: object
      properties:
        filename:
          type: string
        contents:
          type: string
  headers:
    JWT:
      description: jwt bearer
      schema:
        type: string
  securitySchemes:
    accessBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
    refreshBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
