import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const targetDir = process.argv[2];

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.rebuild();

	console.log("copying to " +  targetDir);
	if (!fs.existsSync(targetDir + "/.obsidian/plugins/aerosol-plugin")){
		fs.mkdirSync(targetDir + "/.obsidian/plugins/aerosol-plugin");
	}
	fs.copyFileSync("main.js", targetDir + "/.obsidian/plugins/aerosol-plugin/main.js")
	fs.copyFileSync("styles.css", targetDir + "/.obsidian/plugins/aerosol-plugin/styles.css")
	fs.copyFileSync("manifest.json", targetDir + "/.obsidian/plugins/aerosol-plugin/manifest.json")

	process.exit(0);
}
