name: Lint 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
   
    - name: Update dependencies
      run: |
        npm update
        npm install

    - name: Run ESLint
      run: |
        npm install eslint
        npx eslint . --ext .js,.jsx,.ts,.tsx