name: Lint 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: |
        npm i -g pnpm
        pnpm i

    - name: Run ESLint
      run: npx eslint .