name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install linters
        run: npm install --save-dev eslint prettier

      - name: Run ESLint
        run: npx eslint . --format stylish
        continue-on-error: true  # Prevent workflow from stopping due to ESLint errors

      - name: Run Prettier and auto-format
        run: npx prettier --write .

        #TODO: add github-actions[bot] permissions to write to this repo
      - name: Commit and push Prettier changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Auto-format code with Prettier"
          git push
        continue-on-error: true  # Allows Prettier fixes even if other steps fail