name: Lint 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install pnpm
      run: npm i -g pnpm
  
    - name: Initialize pnpm workspace
      run: pnpm workspace init
  
    - name: Install dependencies
     run: pnpm install --no-frozen-lockfile

    - name: Run ESLint
      run: npx eslint .