name: Lint Code

on:
  push:
    branches: [main, github-lint-on-commit]  # Adjust branches as needed
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust to match your project

      - name: Install dependencies
        run: npm ci  # Ensures a clean install

      - name: Run ESLint
        run: npx eslint . --ext .js,.ts --max-warnings=0
